### ISSUE TITLE
choice[@n = 'eol'] processing

### ISSUE THREAD

**Issue by jawalsh** [Conal-Tuohy/swinburne#11]
Some files have this structure to regularize end-of-line hyphenation found in the original source:

```xml
<choice n="eol">
      <reg>undramatic</reg>
      <orig>undra-matic</orig>
</choice>
```

The above example is found in **acs0000001-01.xml** in the component div with `@xml:id` **acs0000001-01-i000**.

In the case of `choice[@n = 'eol']` we want to display the regularized (`reg`) option, but currently the original (`orig`) is being displayed. I think this is probably the case for all `choice[reg and orig]` elements; we want to display `reg`.

**Comment by Conal-Tuohy** [comment]
For the record the issue is here was related to https://github.com/Conal-Tuohy/swinburne/commit/930c11257aaecde73ac944eb9fa38d6d18d4e768 in which the `p5-to-html.xsl` stylesheet output the content of a `choice/reg` in the HTML text, while capturing the `choice/orig` in a `data-orig` attribute in the HTML, so that the regularised form was indexed, but then when the HTML was fed to Solr an additional pipeline step would remove the regularised form and replace it with the `data-orig` step. The point of that was so as to be able to search for `Aeschylean` and find `Æschylean`.

However, that's not the behaviour we want with the "end of line" choices. I modified the `choice` template so that it didn't apply when `@n='eol'`, and hence didn't create the `data-orig` attribute.
