### ISSUE TITLE
Indexing error

### ISSUE THREAD

**Issue by jawalsh** [Conal-Tuohy/swinburne#18]
When attempting to rebuild the index, recieved the following error:

| Error message | Error code	| File | Line | Column |
| :--- | :--- | :--- | :--- | :--- |
| Errors were reported during stylesheet compilation | | file:/etc/xproc-z/swinburne/xproc/p5-processing.xpl | 144 | 17 |

**Comment by Conal-Tuohy** [comment]
I need to get better error reporting here; there are multiple things that can go wrong such as a failure to perform the TEI-to-Solr-record conversion and a failure to store the resulting record in Solr (Solr may be down, or the supplied record may not conform to the schema). Unfortunately Calabash's error reporting is a bit weak; if you allow a runtime error to occur, the XProc error terminates the XProc runtime, and you can catch the Java exception which includes a helpful Java strack trace, and some detailed information is dumped to the log, but if you catch the error in XProc (with `<p:try><p:group>...</p:group><p:catch>...</p:catch></p:try>`) the `<c:error>` document you obtain is a bit skimpy on details. 

To debug it I removed the XProc try/catch construct and got this in Tomcat's log:
> ERROR: file:/etc/xproc-z/swinburne/xslt/evaluate-rendition-selectors.xsl:343:1705:XPST0003:Inline functions require support for higher-order-functions, which needs Saxon-PE or higher

On my desktop machine I'd already upgraded the XProc interpreter to a more recent version, including the latest version of Saxon, in which support for higher-order functions is no longer restricted to the commercially licensed edition. (The selector-evaluation stylesheet uses higher order functions.)

To fix that I upgraded XProc-Z by downloading the most recent xproc-z.war file and overwriting the existing file in /etc/xproc-z/xproc-z.war

https://github.com/Conal-Tuohy/XProc-Z/releases/tag/1.5

Now I have a different problem,, which I'll investigate next. I think @jawalsh that you will already have the latest XProc-Z, so I'm guessing I'm now at least working on the same issue you are facing.

**Comment by Conal-Tuohy** [comment]
With the try/catch still commented out I got this in the log
```
Message: acs0000001-05-i028.xml
Type error at char 268 in expression in xsl:attribute/@select on line 337 column 7 of p5-to-html.xsl:
  XPTY0004  A sequence of more than one item is not allowed as the first argument of
  fn:tokenize() ("#ti-0", "#ti-0") 
  In template rule with match="*" on line 323 of p5-to-html.xsl
     invoked by xsl:next-match at file:/etc/xproc-z/swinburne/xslt/p5-to-html.xsl#266
  In template rule with match="element(Q{http://www.tei-c.org/ns/1.0}l)" on line 262 of p5-to-html.xsl
     invoked by xsl:apply-templates at file:/etc/xproc-z/swinburne/xslt/p5-to-html.xsl#302
  In template rule with match="element(Q{http://www.tei-c.org/ns/1.0}l)" on line 300 of p5-to-html.xsl
     invoked by xsl:apply-templates at file:/etc/xproc-z/swinburne/xslt/p5-to-html.xsl#378
  In template rule with match="*" on line 375 of p5-to-html.xsl
     invoked by xsl:apply-templates at file:/etc/xproc-z/swinburne/xslt/p5-to-html.xsl#317
  In template rule with match="*" on line 314 of p5-to-html.xsl
     invoked by xsl:apply-templates at file:/etc/xproc-z/swinburne/xslt/p5-to-html.xsl#378
  In template rule with match="*" on line 375 of p5-to-html.xsl
     invoked by xsl:apply-templates at file:/etc/xproc-z/swinburne/xslt/p5-to-html.xsl#317
  In template rule with match="*" on line 314 of p5-to-html.xsl
     invoked by xsl:apply-templates at file:/etc/xproc-z/swinburne/xslt/p5-to-html.xsl#378
  In template rule with match="*" on line 375 of p5-to-html.xsl
     invoked by xsl:apply-templates at file:/etc/xproc-z/swinburne/xslt/p5-to-html.xsl#317
  In template rule with match="*" on line 314 of p5-to-html.xsl
     invoked by xsl:apply-templates at file:/etc/xproc-z/swinburne/xslt/p5-to-html.xsl#79
  In template rule with match="document-node()/element(Q{http://www.tei-c.org/ns/1.0}TEI)" on line 20 of p5-to-html.xsl
     invoked by built-in template rule (text-only)
```
So the `tokenize` function is spitting the dummy over being passed a sequence with cardinality greater than 1. 
The expression in question is:
```xpath
string-join(
	(
		concat('tei-', local-name()),
		for $type in tokenize(@type) return concat('type-', $type),
		for $place in tokenize(@place) return concat('place-', $place),
		for $rendition in 
			tokenize(
				if (@rendition) then 
					@rendition
				else
					$tag-usage[@gi=local-name(current())]/@rendition
			) 
		return 
			concat('rendition-', substring-after($rendition, '#')),
		if (@hand) then 'hand' else ()
	),
	' '
)
```
Looking at that, most of the calls to `tokenize` are passing an attribute value which could only be a singular item, so the underlying issue could only be that the sub-expression `$tag-usage[@gi=local-name(current())]/@rendition` returns a sequence of multiple values instead of a single value. 
Looking at the TEI document itself, is seems that it contains a duplicated `encodingDesc` and hence a duplicated `tagsDecl` and `tagUsage` elements. I'll address that bug which I guess is in the system of transclusions.

**Comment by Conal-Tuohy** [comment]
I didn't get back to this today until just recently. I wondered if the duplicate header elements might have just been just a relic from when I'd run the ingest pipeline months ago, and lo, my guess was correct. I ran the ingest and transclusion steps, and then the indexing step was able to run without throwing an error.

I'm away in NZ and brought my laptop with an old Swinburne VM which I hadn't used in months. I'd done a `git pull` to refresh it, but that's why it still had the old XProc-Z war file, and old `p5/result/*.xml` files. 

So I'm hoping that the stale XProc interpreter actually is the problem you've got. If not, let me know, but for now I'm closing this issue in a fit of optimism
